import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Hero from "../components/Heading";
import Content from "../components/Content";
import Refresh from "../components/Refresh";
import DigitalClock from '../components/DigitalClock';
import { getDataFromEndpoint } from "@/components/src/helpers";

const inter = Inter({ subsets: ["latin"] });


// export async function getStaticProps(){
//   const data = await getDataFromEndpoint('https://jsonplaceholder.typicode.com/users');
//   return {
//     props: {data}
//   }
// }
export async function getServerSideProps(){
  const data = await getDataFromEndpoint('https://jsonplaceholder.typicode.com/users');
  return {
    props: {data}
  }
}

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>MDAT-Console</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="custom-bg">
        <div className="grid grid-cols-2 text-white text-xs">
          <div className="col-span-1 mt-2">
            <Refresh/>
          </div>
          <div className="col-span-1 mt-2 justify-self-end mr-8">
            <DigitalClock />
          </div>
          <div className='col-span-2 mt-2'>
            <Content content={data}/>
          </div>

        </div>

        {/* <Hero heading='MDAT Admin Console' message='Enter password: '></Hero> */}
      </main>
    </>
  );
}
